const mainBlock = document.querySelector(".main-block");
const block1 = document.querySelector(".block-1");
const block2 = document.querySelector(".block-2");
const title1 = document.querySelector(".title-1");
const title2 = document.querySelector(".title-2");
const text1 = document.querySelector(".text-block-1");
const text2 = document.querySelector(".text-block-2");
const logo1 = document.querySelector(".logo-1");
const logo2 = document.querySelector(".logo-2");
const button1 = document.querySelector(".btn-block-1");
const button2 = document.querySelector(".btn-block-2");

block1.addEventListener("click", function () {
    this.classList.add('animation-block1');
    block2.classList.remove('animation-block2');
    block2.classList.add('animation-block2-1');
    block1.classList.remove('animation-block1-2');
    mainBlock.style.flexDirection = "row";
    logo1.classList.add('animation-logo1');
    logo2.classList.add('animation-logo2-1');
    title1.classList.add('animation-title1');
    title1.classList.remove('animation-title1-2');
    title1.classList.remove('title-2');
    title2.classList.add('animation-title2-1');
    title2.classList.remove('animation-title2');
    button1.classList.add('animation-button1');
    button1.classList.remove('animation-button1-2');
    text1.classList.add('animation-text1');
    text1.classList.remove('text-block-1');
    text1.classList.remove('animation-text1-2');
    text2.classList.remove('animation-text2');
    text2.classList.remove('text-block-2');
    text2.classList.add('animation-text2-1');
    button2.classList.remove('animation-button2');
});

block2.addEventListener("click", function () {
    this.classList.add('animation-block2');
    this.classList.remove('animation-block2-1');
    block1.classList.remove('animation-block1');
    block1.classList.add('animation-block1-2');
    logo1.classList.remove('animation-logo1');
    logo2.classList.add('animation-logo2');
    logo2.classList.remove('animation-logo2-1');
    title1.classList.remove('animation-title1');
    title1.classList.add('animation-title1-2');
    title1.classList.remove('title-2');
    title2.classList.remove('animation-title2-1');
    title2.classList.add('animation-title2');
    button1.classList.remove('animation-button1');
    button1.classList.remove('btn-block-1');
    button1.classList.add('animation-button1-2');
    text1.classList.remove('animation-text1');
    text1.classList.remove('text-block-1');
    text1.classList.add('animation-text1-2');
    text2.classList.add('animation-text2');
    text2.classList.remove('text-block-2');
    button2.classList.add('animation-button2');
});